name: Build and deploy to production a container to Azure Web App - api.py


on: 
  push:
    branches: 
      - main

# Github Actions will run a deployment job that consists of the 5 steps above, each with its own name.
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
      
      
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: gtfastapicd.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
     
     
    - name: Build and push container image to registry 
      run: |
        docker build . -t gtfastapicd.azurecr.io/fastapi-cd:${{ github.sha }}
        docker push gtfastapicd.azurecr.io/fastapi-cd:${{ github.sha }}
        
        
    # nouvelle étape d'exécution des tests unitaires
    - name: Run Unit Tests
      run: |
        docker run gtfastapicd.azurecr.io/fastapi-cd:${{ github.sha }} pytest test_api.py    
        
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastapi-cd'
        images: 'gtfastapicd.azurecr.io/fastapi-cd:${{ github.sha }}'
        slot-name: 'staging'
    
       
    - name: Azure logout
      run: |
        az logout